### PR TITLE
Proposal: add a `style` property to simplify CSS one-off injection

### PR DESCRIPTION
**Pull request by WebReflection**
Even if CSS belongs to the CSS world, having the ability to confine
all component related things in one file is still somehow handy
and often demanded/adopted by the Web development community.

I have tested this with the project _herey_, and I think it might
give wickedElements an extra reason to feel wicked.

For those not needing CSS in components this won't change anything,
but for those looking to ship components as a whole in one file
this is a core game-changer.

Question to the users, if anyone: is `style` the right propety to use?
Would this interfere with your component definition/life cycle?

I've thought some might use `this.style = this.el.style` in some component,
and I want to be sure this is backward compatible friendly.

Thanks to whoever would like to express an opinion.

### CODE REVIEW

**Comment by grommett** [comment]
@WebReflection I like this idea. 👍 I think it's useful _and_ pragmatic. 

You bring up a really good point about the use of the variable `style`, though. I can see how the usage example you sited might be an issue. I'm curious what other users of this library say, but in my experience the elements are already styled the old school way 👴.

If `style` is an issue maybe consider `css`?

**Comment by WebReflection** [comment]
> I can see how the usage example you sited might be an issue.

theoretically there is no issue in assigning `this.style = this.el.style` because the inherited style is used only once at component definition, and never again.

The gotcha is if you do `if (!this.style) this.style = this.el.style` 'cause that inherited `style` will be there, if used.

I think maybe I should just get rid of the `style` property after definition 'cause in case of classes it doesn't interfere with the instance, being static and not in prototype, while in case of objects won't be there ... yet the fact I'm thinking so much about this is a hint `style` is likely not the best name, 'cause I can see some doing `get style() { return this.el.style; }` too, at component definition, and that'd be doomed with this change.

> If style is an issue maybe consider css?

I've thought about this too. The `style` was in my mind semantic with what happens: a `<style>` element is appended at component definition. The `css` might still feel semantic, but then I'm sure somebody would feel more comfortable in writing `CSS` instead of `css` ... but maybe I am overthinking this.

`styleSheet` is less friendly for non English mother tongue, since I've mistakenly written it myself few times wrongly when I didn't know English at all, so that `styleShit` or `stylesheet` (as single word) might be a curse too.

I guess when they say naming in software is hard, this is yet another example 😅

If there's any other suggestion, it'd be more than welcome, thanks!

**Comment by WebReflection** [comment]
btw ... I think I'll just go with `style`, 'cause reaching the element style is already super trivial and having a style attached to the component that drives the element feels like a bad pattern anyway.

Thanks for the little brainstorming.

**Comment by WebReflection** [comment]
added [style.html](https://webreflection.github.io/wicked-elements/test/style.html) test and fixed tests in IE9 and IE10 + tested all browsers show the style when present.

brotli version still under 2048 bytes 🎉

**Pull request merged**
