### PR TITLE
add bundled es module

### PR DESCRIPTION
**Pull request by simonmcmanus**
generates bundled es modules:

* `./bundle.mjs`
* `./bundle-min.mjs`

It can then be called from the browser with an import (once published):

```
<html>
<script type="module">
   import  { define } from 'https://unpkg.com/wicked-elements/bundle-min.mjs'
</script>
</html>

```

or dynamically:

```
const  { define } = await import('https://unpkg.com/wicked-elements/bundle-min.mjs')
```

# To Test

```
http-server
npm i
npm run build
```

1: Browse to: 

http://localhost:8080/

2: browser console: 
```
const  { define } = await import('http://localhost:8080/bundle.mjs')
```

# Notes

* possibly some better ways to share the rollup config between files
* I didn't update the size script
* I was testing this locally and thought it might be useful.

### CODE REVIEW

**Comment by WebReflection** [comment]
I don't think I'll ever land an `.mjs` file in my projects, but I'll make _wickedElements_ and _hookedElements_ [dual-module compatible](https://medium.com/@WebReflection/a-nodejs-dual-module-deep-dive-8f94ff56210e).

**Comment by WebReflection** [comment]
Done, you can now import wicked-elements without issues.

**Comment by simonmcmanus** [comment]
Ahh thanks, some useful bits in that post. I will have a look later at your changes.  

Out of interest, Is your objection to `.mjs` files just compatibility with commonJS or is there something else?

**Comment by WebReflection** [comment]
`.mjs` don't play well in the wild: not all Web servers understand the file, so the app breaks and fail at loading `.mjs` modules + not all editors understand the file + bundlers don't care + it's really not needed at all, as explained in that post + it's redundant, as you load modules via `<script type="module">` hence there's no need to specify in the extension is a module, it's already explicitly a module + once bundled, it's not a module anymore, it's an app, so that calling it `.mjs` doesn't make sense, as the app wouldn't export anything.

**edit** in few words there are literally 0 real-world benefits in using `.mjs`, but possible issues in choosing such extension. As D. Crockford once said:

> if there are two ways of doing one thing, and one always works, and the other doesn't, always choose the one that always works (more or less it was this sentence)

`.mjs` fails in most PHP based hosts too, so I personally never ever want to use this format, and rather fallback to `.cjs` when strictly needed (explained in that post too).

**Comment by simonmcmanus** [comment]
thanks, very helpful 👍

**Pull request closed without merging**
